name: Build Godot Project

on:
  pull_request:
    branches:
     - master
  push:
    branches:
      - master


jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: DDOn Tools
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.slug.outputs.sha8 }}
          release_name: Release ${{ steps.slug.outputs.sha8 }}
          draft: false
          prerelease: false