name: Build Godot Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: Windows
          file: DDOn-Tools.exe
#        - name: MacOS
#          file: DDOn-Tools.zip
#        - name: Linux
#          file: DDOn-Tools
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Build
        id: build
        uses: yeslayla/build-godot-action@v1.5.0
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: "false"
      - name: Zip
        working-directory: ${{ github.workspace }}
        run: zip -qq -r DDOn-Tools_${{ matrix.platform.name }}-${{ steps.slug.outputs.sha8 }}.zip *
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: DDOn-Tools_${{ matrix.platform.name }}-${{ steps.slug.outputs.sha8 }}.zip
          tag_name: release-${{ steps.slug.outputs.sha8 }}
          name: Release ${{ steps.slug.outputs.sha8 }}
          draft: false
          prerelease: true