name: Build Godot Project

on:
  pull_request:
    branches:
     - master
  push:
    branches:
      - master


jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      slug: ${{ steps.slug.outputs.sha8 }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.slug.outputs.sha8 }}
          release_name: Release ${{ steps.slug.outputs.sha8 }}
          draft: false
          prerelease: true
  build:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        platform: [windows]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: DDOn-Tools
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Rename build executable
        id: rename
        working-directory: ${{ github.workspace }}
        run: |
          mkdir renamedBuildOutput
          cp ${{ steps.build.outputs.build }}/* renamedBuildOutput/
          cp "renamedBuildOutput/DDOn-Tools" "renamedBuildOutput/DDOn-Tools.exe"
      - name: Zip build
        working-directory: ${{ github.workspace }}
        run: zip -qq -r ${{ matrix.platform }}-${{ needs.release.outputs.sha8 }}.zip renamedBuildOutput
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ matrix.platform }}-${{ needs.release.outputs.sha8 }}.zip
          asset_name: ddon-tools_${{ matrix.platform }}-${{ needs.release.outputs.sha8 }}.zip
          asset_content_type: application/gzip